version: '2'
services:

  influxdb:
    container_name: influxdb
    image: influxdb:1.2
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /code/data/influxdb:/var/lib/influxdb
    network_mode: bridge

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: host

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:0.10.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${EXPOSE_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 911
      KAFKA_CREATE_TOPICS: "test:${NUM_PARTITIONS}:1"
      KAFKA_ZOOKEEPER_CONNECT: ${EXPOSE_IP}:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /data/kafka:/kafka
    network_mode: host

  node0:
    container_name: node0
    image: galtsev/dstor
    command: dstor storage-node -partitions 0,1,2,3
    ports:
      - "8780:8787"
    environment:
      DSTOR_ZK_HOST: ${EXPOSE_IP}:2181
      DSTOR_KAFKA_HOST: ${EXPOSE_IP}:9092
      DSTOR_ADVERTIZE_HOST: ${EXPOSE_IP}:8780
      DSTOR_NUM_PARTITIONS: ${NUM_PARTITIONS}
    volumes:
      - /data/leveldb0:/mnt/leveldb
    network_mode: bridge

  node1:
    container_name: node1
    image: galtsev/dstor
    command: dstor storage-node -partitions 4,5,6,7
    ports:
      - "8781:8787"
    environment:
      DSTOR_ZK_HOST: ${EXPOSE_IP}:2181
      DSTOR_KAFKA_HOST: ${EXPOSE_IP}:9092
      DSTOR_ADVERTIZE_HOST: ${EXPOSE_IP}:8781
      DSTOR_NUM_PARTITIONS: ${NUM_PARTITIONS}
    volumes:
      - /data/leveldb1:/mnt/leveldb
    network_mode: bridge


  proxy:
    container_name: proxy
    image: galtsev/dstor
    command: dstor proxy
    environment:
      DSTOR_ZK_HOST: ${EXPOSE_IP}:2181
      DSTOR_KAFKA_HOST: ${EXPOSE_IP}:9092
      DSTOR_NUM_PARTITIONS: ${NUM_PARTITIONS}
    network_mode: host

  standalone:
    container_name: dstor
    image: galtsev/dstor
    command: dstor standalone
    ports:
      - "8787:8787"
    volumes:
      - /data/leveldb:/mnt/leveldb
    network_mode: host
