influx:
  url: http://localhost:8086
  database: test
  measurement: ms
  batch_size: 1000
  flush_delay: 50
kafka:
  hosts:
  - localhost:9092
  topic: test
  num_partitions: 4
  partitions:
  - 0
  batch_size: 200
  flush_delay: 50
  serializer: msgp
gen:
  mode: "seq"
  start: 2017-04-09 00:00
  end: 2017-04-10 00:00
  count: 10000000
  tags: 20
reportingserver:
  addr: localhost:8787
receptorserver:
  addr: localhost:8787
client:
  batch_size: 10
leveldb:
  path: /home/dan/data/leveldb
  batchsize: 1000
  flushdelay: 50
one_shot: false

