influx:
  url: http://localhost:8086
  database: test
  measurement: ms
zookeeper:
  servers:
    - localhost:2181
kafka:
  hosts:
  - localhost:9092
  topic: test
  num_partitions: 8
  partitions: [0, 1, 2, 3]
  serializer: msgp
  batch:
    batch_size: 200
    flush_delay: 50
gen:
  mode: "geom"
  start: 2017-04-11 00:00
  end: 2017-04-13 00:00
  count: 40000000
  tags: 2000
  backend: leveldb
#leveldb-standalone
server:
  addr: localhost:8787
  backends:
    leveldb: leveldb
  storage: leveldb
  reporter: leveldb
  consume_partitions: [0, 1, 2, 3]
# # leveldb-node
# server:
#   addr: localhost:8787
#   backends:
#     storage: leveldb
#   storage: storage
# # leveldb-proxy
# server:
#   addr: localhost:8787
#   backends:
#     storage: kafka
#     reporter: remote
#   storage: storage
#   reporter: reporter

client:
  batch_size: 10
leveldb:
  path: /home/dan/data/leveldb
  num_partitions: 4
  partitions: [0, 1, 2, 3]
batch:
  batch_size: 1000
one_shot: false
file_path: "/home/dan/data/generated.msgp"

