influx:
  url: http://localhost:8086
  database: test
  measurement: ms
kafka:
  hosts:
  - localhost:9092
  topic: test
  num_partitions: 4
  partitions:
  - 0
  serializer: msgp
gen:
  mode: "geom"
  start: 2017-04-23 00:00
  end: 2017-04-24 00:00
  count: 10000000
  tags: 20
server:
  addr: localhost:8787
  backend: leveldb
client:
  batch_size: 10
leveldb:
  path: /home/dan/data/leveldb
  ttl: 24h
one_shot: false

