influx:
  url: http://localhost:8086
  database: test
  measurement: ms
kafka:
  hosts:
  - localhost:9092
  topic: test
  num_partitions: 4
  partitions:
  - 0
  serializer: msgp
gen:
  mode: "geom"
  start: 2017-04-10 00:00
  end: 2017-04-16 00:00
  count: 20000000
  tags: 2000
  backend: file
#leveldb-standalone
server:
  addr: localhost:8787
  backends:
    leveldb: leveldb
  storage: leveldb
  reporter: leveldb
# # leveldb-node
# server:
#   addr: localhost:8787
#   backends:
#     storage: leveldb
#   storage: storage
# # leveldb-proxy
# server:
#   addr: localhost:8787
#   backends:
#     storage: kafka
#     reporter: remote
#   storage: storage
#   reporter: reporter

client:
  batch_size: 10
leveldb:
  path: /tmp/leveldb
  compact_before: 2017-04-13 12:00
batch:
  batch_size: 1000
one_shot: false
file_path: "/home/dan/data/generated.msgp"

