influx:
  url: http://localhost:8086
  database: test
  measurement: ms
kafka:
  hosts:
  - localhost:9092
  topic: test
  num_partitions: 4
  partitions:
  - 0
  serializer: msgp
gen:
  mode: "geom"
  start: 2017-04-15 00:00
  end: 2017-04-20 00:00
  count: 50000000
  tags: 2000
server:
  addr: localhost:8787
  backend: leveldb
client:
  batch_size: 10
leveldb:
  path: /tmp/leveldb
  compact_before: 2017-04-13 12:00
batch:
  batch_size: 1000
one_shot: false

